language: node_js
node_js: '10'
services: mongodb
env:
  matrix:
  - MONGODB_URI=mongodb://localhost:27017/test
deploy:
  provider: heroku
  app:
    master: nanny-now-production
    dev: nanny-now-staging
  api_key:
    secure: Gi+CntsVLh0lsj8HJ3hmakEeLBW3CbWDLgPmP5vmTi+1+w8bozFkemyz0MtcdkzyE6T/7b7aXPIXEjTlJq4DfvNuk+05XBuEs26QqE3d2Le51DrQArYlRL/LCqnaPFajvLX3NhCi74i+U696B1EymQa6b8QRTRGCmaMmcPdtX8KpHzpehAA+L1o47I+1TGgrFJVpJlZeiDGSZhYqfE5TGYthSLPVySPrDyf0F3BUe6qPNRGMV57p8BL1klp4lFMJ+hBTxatGIrZzBHVSN/fCQVRCMlDy3ERQAQNIzEUk9ocuqVI5fhfIOA7dnoqRiol/7W6cx9kGI/APuLvIbrYJfxv/VbLNVEe0T7/xwISlOnHZ1lOB1FYJLDQo55DjW54XtA3ECOVWtu55k8paMQ6CjMve5Mvwet/bqsH8v9UxQPhKhRMyN4ur+8g5qKPyggNAplbQyeiLOpzL/JRUrQCkDwO84F40bVg2/b5+ni+DgdENJOHy366UNMk3zm2D+fX2qjLZKvobzfkr5rgJ2La+KcOXR9NQwkgJe90dS7H5OrVfh6OD0tSc4t3nDSUQVc7u4C05ogNxFYwD7org0jT5ojkaaNSr66G5jPh+YxWZ+bUTuJ53DhClsKu+PiSG2R6kEt+iqwuGyrh94GMqIIkYCZjalyAC3TdyZtaE9QVAedw=
